apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sc-demo-keyvault-csi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" # change it to the User-assigned Managed Identity Client ID attached to key vault
    keyvaultName: "" # Key vault name You assigned at Terraform creation
    objects: |
      array:
        - |
          objectName: sender-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: retreiver-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: retreiver-uri
          objectType: secret
          objectVersion: ""
    tenantId: "" # Your Tenant ID
  secretObjects:
    # Create a Kubernetes secret for sender-password
    - data:
        - key: kv-sender-password
          objectName: sender-password
      secretName: sender-password-secret
      type: Opaque
    # Create a Kubernetes secret for retreiver-password
    - data:
        - key: kv-retreiver-password
          objectName: retreiver-password
      secretName: retreiver-password-secret
      type: Opaque
    # Create a Kubernetes secret for retreiver-uri
    - data:
        - key: kv-retreiver-uri
          objectName: retreiver-uri
      secretName: retreiver-uri-secret
      type: Opaque
